#
# You will need to insert the base64 encoded secrets below.
#

apiVersion: v1
kind: Secret
metadata:
  name: datadog-secret
  labels:
    app: "datadog"
type: Opaque
data:
  api-key: "some base64 api key"
  app-key: "some base64 app key"
---
apiVersion: v1
kind: Secret
metadata:
  name: datadog-auth-token
type: Opaque
data:
  token: "some 32 character string, base64 encoded"
