#
# You will need to insert the base64 encoded secret below.
#

apiVersion: v1
kind: Secret
metadata:
  name: datadog-secret
  labels:
    app: "datadog"
type: Opaque
data:
  api-key: "some base64 api key"
---
