apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-dw-send-email
spec:
  replicas: 5
  selector:
    matchLabels:
      app: worker-dw-send-email
  template:
    metadata:
      labels:
        app: worker-dw-send-email
        type: worker
      annotations:
        ad.datadoghq.com/worker-dw-send-email.logs: '[{"source":"worker","service":"dw-send-email"}]'
    spec:
      containers:
      - image: 194396987458.dkr.ecr.us-east-1.amazonaws.com/dreamwidth/worker:latest
        name: worker-dw-send-email
        command: ["bash"]
        args: ["/opt/startup-prod.sh", "bin/worker/dw-send-email", "-v"]
        resources:
          requests:
            cpu: 100m
            memory: 300M
        volumeMounts:
        - name: config
          mountPath: /dw/etc
          readOnly: true
        env:
        - name: DOGSTATSD_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
      volumes:
      - name: config
        secret:
          secretName: dw-config
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: worker-dw-send-email
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker-dw-send-email
  minReplicas: 5
  maxReplicas: 20
  metrics:
  - type: External
    external:
      metricName: dw.sqs.approx_messages
      metricSelector:
        matchLabels:
            queue: dw-prod-dw-task-sendemail
      targetAverageValue: 20
