apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-esn-process-sub
spec:
  replicas: 10
  selector:
    matchLabels:
      app: worker-esn-process-sub
  template:
    metadata:
      labels:
        app: worker-esn-process-sub
      annotations:
        ad.datadoghq.com/worker-esn-process-sub.logs: '[{"source":"worker","service":"esn-process-sub"}]'
    spec:
      containers:
      - image: 194396987458.dkr.ecr.us-east-1.amazonaws.com/dreamwidth/worker:latest
        name: worker-esn-process-sub
        command: ["bash"]
        args: ["/opt/startup-prod.sh", "bin/worker/esn-process-sub", "-v"]
        resources:
          requests:
            cpu: 50m
            memory: 300M
        volumeMounts:
        - name: config
          mountPath: /dw/etc
          readOnly: true
        env:
        - name: DOGSTATSD_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
      volumes:
      - name: config
        secret:
          secretName: dw-config
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-esn-process-sub
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker-esn-process-sub
  minReplicas: 10
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100
