apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-esn-fired-event
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-esn-fired-event
  template:
    metadata:
      labels:
        app: worker-esn-fired-event
        type: worker
      annotations:
        ad.datadoghq.com/worker-esn-fired-event.logs: '[{"source":"worker","service":"esn-fired-event"}]'
    spec:
      containers:
      - image: 194396987458.dkr.ecr.us-east-1.amazonaws.com/dreamwidth/worker:latest
        name: worker-esn-fired-event
        command: ["bash"]
        args: ["/opt/startup-prod.sh", "bin/worker/esn-fired-event", "-v"]
        resources:
          requests:
            cpu: 50m
            memory: 300M
        volumeMounts:
        - name: config
          mountPath: /dw/etc
          readOnly: true
        env:
        - name: DOGSTATSD_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
      volumes:
      - name: config
        secret:
          secretName: dw-config
