name: dw-test build

on:
  #push:
  workflow_dispatch:

env:
  IMAGE_NAME: test
  TASK_NAME: web-canary

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::194396987458:role/dw-github-actions
          aws-region: us-east-1

      - name: Get task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition arn:aws:ecs:us-east-1:194396987458:task-definition/$TASK_NAME \
            --region "us-east-1"
